/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProjectController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;
import util.TaskTableModel;

public class MainScreen extends javax.swing.JFrame {

    ProjectController projectController;
    TaskController taskController;

    public void initDataController() {
        projectController = new ProjectController();
        taskController = new TaskController();
    }

    DefaultListModel projectsModel;
    TaskTableModel taskModel;

    public void initComponentstModel() {
        projectsModel = new DefaultListModel();
        loadProjects();

        taskModel = new TaskTableModel();
        tabelaTarefas.setModel(taskModel);

        loadTasks();

    }

    public void loadTasks() {
        List<Task> tasks = taskController.getByProjectId(1);
        taskModel.setTarefas(tasks);

    }
    
    private void loadTasks(int projectId) {
        List<Task> tasks = taskController.getByProjectId(projectId);

        taskModel.setTarefas(tasks);
        showJTableTasks(!tasks.isEmpty());
    }

    public void loadProjects() {
        List<Project> projects = projectController.getAll();
        projectsModel.clear();

        for (int i = 0; i < projects.size(); i++) {
            Project project = projects.get(i);
            projectsModel.addElement(project);

            projetos.setModel(projectsModel);

        }
    }

    public MainScreen() {
        initComponents();
        decorarTabela();
        initDataController();
        initComponentstModel();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelaListaTarefas = new javax.swing.JScrollPane();
        tabelaTarefas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cabecalho = new javax.swing.JPanel();
        cabecalhoTitulo = new javax.swing.JLabel();
        cabecalhoSubtitulo = new javax.swing.JLabel();
        painelProjetos = new javax.swing.JPanel();
        painelProjetosIcone = new javax.swing.JLabel();
        painelProjetosTitulo = new javax.swing.JLabel();
        listaProjetos = new javax.swing.JScrollPane();
        projetos = new javax.swing.JList<>();
        painelTarefa = new javax.swing.JPanel();
        painelTarefaTitulo = new javax.swing.JLabel();
        painelTarefaIcone = new javax.swing.JLabel();
        painelListaTarefas = new javax.swing.JPanel();
        painelListaVazia = new javax.swing.JPanel();
        painelListaProjetos = new javax.swing.JPanel();
        tituloListaVazia = new javax.swing.JLabel();

        tabelaListaTarefas.setBackground(new java.awt.Color(251, 248, 241));

        tabelaTarefas.setBackground(new java.awt.Color(251, 248, 241));
        tabelaTarefas.setFont(new java.awt.Font("JetBrains Mono Light", 0, 12)); // NOI18N
        tabelaTarefas.setForeground(new java.awt.Color(84, 186, 185));
        tabelaTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa concluida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaTarefas.setRowHeight(40);
        tabelaTarefas.setSelectionBackground(new java.awt.Color(233, 218, 193));
        tabelaTarefas.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tabelaTarefas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaTarefas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaTarefas.setShowGrid(false);
        tabelaTarefas.setShowHorizontalLines(true);
        tabelaTarefas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaTarefasMouseClicked(evt);
            }
        });
        tabelaListaTarefas.setViewportView(tabelaTarefas);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 800));
        setSize(new java.awt.Dimension(400, 600));

        jPanel1.setBackground(new java.awt.Color(233, 218, 193));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 600));

        cabecalho.setBackground(new java.awt.Color(247, 236, 222));

        cabecalhoTitulo.setFont(new java.awt.Font("JetBrains Mono Light", 1, 24)); // NOI18N
        cabecalhoTitulo.setForeground(new java.awt.Color(84, 186, 185));
        cabecalhoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cabecalhoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone app.png"))); // NOI18N
        cabecalhoTitulo.setText("Gerenciador de projetos App");

        cabecalhoSubtitulo.setForeground(new java.awt.Color(84, 186, 185));
        cabecalhoSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cabecalhoSubtitulo.setText("Anote tudo, não esqueça nada!");

        javax.swing.GroupLayout cabecalhoLayout = new javax.swing.GroupLayout(cabecalho);
        cabecalho.setLayout(cabecalhoLayout);
        cabecalhoLayout.setHorizontalGroup(
            cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cabecalhoLayout.createSequentialGroup()
                        .addComponent(cabecalhoSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(cabecalhoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        cabecalhoLayout.setVerticalGroup(
            cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabecalhoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(cabecalhoSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelProjetos.setBackground(new java.awt.Color(251, 248, 241));

        painelProjetosIcone.setFont(new java.awt.Font("JetBrains Mono Light", 1, 18)); // NOI18N
        painelProjetosIcone.setForeground(new java.awt.Color(84, 186, 185));
        painelProjetosIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adicionar-projeto.png"))); // NOI18N
        painelProjetosIcone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelProjetosIconeMouseClicked(evt);
            }
        });

        painelProjetosTitulo.setFont(new java.awt.Font("JetBrains Mono Light", 1, 18)); // NOI18N
        painelProjetosTitulo.setForeground(new java.awt.Color(84, 186, 185));
        painelProjetosTitulo.setText("Projeto");

        javax.swing.GroupLayout painelProjetosLayout = new javax.swing.GroupLayout(painelProjetos);
        painelProjetos.setLayout(painelProjetosLayout);
        painelProjetosLayout.setHorizontalGroup(
            painelProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelProjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelProjetosTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelProjetosIcone)
                .addContainerGap())
        );
        painelProjetosLayout.setVerticalGroup(
            painelProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelProjetosTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelProjetosIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        projetos.setBackground(new java.awt.Color(251, 248, 241));
        projetos.setFont(new java.awt.Font("JetBrains Mono Light", 1, 14)); // NOI18N
        projetos.setForeground(new java.awt.Color(84, 186, 185));
        projetos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        projetos.setFixedCellHeight(30);
        projetos.setSelectionBackground(new java.awt.Color(233, 218, 193));
        projetos.setSelectionForeground(new java.awt.Color(51, 51, 51));
        projetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projetosMouseClicked(evt);
            }
        });
        listaProjetos.setViewportView(projetos);

        painelTarefa.setBackground(new java.awt.Color(251, 248, 241));

        painelTarefaTitulo.setFont(new java.awt.Font("JetBrains Mono Light", 1, 18)); // NOI18N
        painelTarefaTitulo.setForeground(new java.awt.Color(84, 186, 185));
        painelTarefaTitulo.setText("Tarefa");

        painelTarefaIcone.setFont(new java.awt.Font("JetBrains Mono Light", 1, 18)); // NOI18N
        painelTarefaIcone.setForeground(new java.awt.Color(84, 186, 185));
        painelTarefaIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adicionar-tarefa.png"))); // NOI18N
        painelTarefaIcone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelTarefaIconeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelTarefaLayout = new javax.swing.GroupLayout(painelTarefa);
        painelTarefa.setLayout(painelTarefaLayout);
        painelTarefaLayout.setHorizontalGroup(
            painelTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTarefaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelTarefaIcone)
                .addGap(15, 15, 15))
        );
        painelTarefaLayout.setVerticalGroup(
            painelTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTarefaLayout.createSequentialGroup()
                        .addComponent(painelTarefaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(painelTarefaIcone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelListaTarefas.setBackground(new java.awt.Color(251, 248, 241));

        painelListaVazia.setBackground(new java.awt.Color(251, 248, 241));

        painelListaProjetos.setBackground(new java.awt.Color(251, 248, 241));

        tituloListaVazia.setFont(new java.awt.Font("JetBrains Mono Light", 1, 14)); // NOI18N
        tituloListaVazia.setForeground(new java.awt.Color(84, 186, 185));
        tituloListaVazia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloListaVazia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/llista-vazia.png"))); // NOI18N
        tituloListaVazia.setText("Nenhuma tarefa por aqui...");
        tituloListaVazia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tituloListaVazia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout painelListaProjetosLayout = new javax.swing.GroupLayout(painelListaProjetos);
        painelListaProjetos.setLayout(painelListaProjetosLayout);
        painelListaProjetosLayout.setHorizontalGroup(
            painelListaProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(painelListaProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelListaProjetosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tituloListaVazia, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        painelListaProjetosLayout.setVerticalGroup(
            painelListaProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(painelListaProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelListaProjetosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tituloListaVazia, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout painelListaVaziaLayout = new javax.swing.GroupLayout(painelListaVazia);
        painelListaVazia.setLayout(painelListaVaziaLayout);
        painelListaVaziaLayout.setHorizontalGroup(
            painelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelListaVaziaLayout.createSequentialGroup()
                .addComponent(painelListaProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        painelListaVaziaLayout.setVerticalGroup(
            painelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelListaProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelListaTarefasLayout = new javax.swing.GroupLayout(painelListaTarefas);
        painelListaTarefas.setLayout(painelListaTarefasLayout);
        painelListaTarefasLayout.setHorizontalGroup(
            painelListaTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
            .addGroup(painelListaTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelListaTarefasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelListaVazia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        painelListaTarefasLayout.setVerticalGroup(
            painelListaTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
            .addGroup(painelListaTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelListaTarefasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(painelListaVazia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listaProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(painelProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelListaTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaProjetos)
                    .addComponent(painelListaTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void painelProjetosIconeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelProjetosIconeMouseClicked
        // TODO add your handling code here:
        ProjectDialogScreen projectDialogScreeen = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
        projectDialogScreeen.setVisible(true);

        projectDialogScreeen.addWindowListener(new WindowAdapter() {

            public void windowClosed(WindowEvent e) {
                loadProjects();
            }
        });
    }//GEN-LAST:event_painelProjetosIconeMouseClicked

    private void painelTarefaIconeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelTarefaIconeMouseClicked
        // TODO add your handling code here:

        TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, rootPaneCheckingEnabled);
        //taskdialogScreen.setProject(null);

        taskDialogScreen.setVisible(true);

        taskDialogScreen.addWindowListener(new WindowAdapter() {

            public void windowClosed(WindowEvent e) {
                loadTasks();
            }
        });
    }//GEN-LAST:event_painelTarefaIconeMouseClicked

    private void tabelaTarefasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaTarefasMouseClicked

        int rowIndex = tabelaTarefas.rowAtPoint(evt.getPoint());
        int columnIndex = tabelaTarefas.columnAtPoint(evt.getPoint());
        
        switch (columnIndex) {
            case 3:
                Task task = taskModel.getTarefas().get(rowIndex);
                taskController.update(task);
                break;
            default:
                throw new AssertionError();
        }
        
        

        

    }//GEN-LAST:event_tabelaTarefasMouseClicked

    private void projetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projetosMouseClicked
        // TODO add your handling code here:
        int projectIndex = projetos.getSelectedIndex();
        Project project = (Project) projectsModel.get(projectIndex);
        
        loadTasks(project.getId());
        
    }//GEN-LAST:event_projetosMouseClicked

    private void showJTableTasks(boolean isEmptyTable) {
       if (isEmptyTable) {
            if (jPanelEmptyTasksLayout.isVisible()) {
                jPanelEmptyTasksLayout.setVisible(false);
                jPanelEmptyTasks.remove(jPanelEmptyTasksLayout);
            }

            jPanelEmptyTasks.add(jScrollPaneTasks);
            jScrollPaneTasks.setVisible(true);
            jScrollPaneTasks.setSize(jPanelEmptyTasks.getWidth(), jPanelEmptyTasks.getHeight());
        } else {
            if (jScrollPaneTasks.isVisible()) {
                jScrollPaneTasks.setVisible(false);
                jPanelEmptyTasks.remove(jScrollPaneTasks);
            }

            jPanelEmptyTasks.add(jPanelEmptyTasksLayout);
            jPanelEmptyTasksLayout.setVisible(true);
            jPanelEmptyTasksLayout.setSize(jPanelEmptyTasks.getWidth(), jPanelEmptyTasks.getHeight());
        }
                
    }
    
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    public void decorarTabela() {

        tabelaTarefas.getTableHeader().setFont(new Font("JetBrains Mono Light", Font.BOLD, 14));
        tabelaTarefas.getTableHeader().setBackground(new Color(84, 186, 185));
        tabelaTarefas.getTableHeader().setForeground(new Color(251, 248, 241));

        tabelaTarefas.setAutoCreateRowSorter(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cabecalho;
    private javax.swing.JLabel cabecalhoSubtitulo;
    private javax.swing.JLabel cabecalhoTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane listaProjetos;
    private javax.swing.JPanel painelListaProjetos;
    private javax.swing.JPanel painelListaTarefas;
    private javax.swing.JPanel painelListaVazia;
    private javax.swing.JPanel painelProjetos;
    private javax.swing.JLabel painelProjetosIcone;
    private javax.swing.JLabel painelProjetosTitulo;
    private javax.swing.JPanel painelTarefa;
    private javax.swing.JLabel painelTarefaIcone;
    private javax.swing.JLabel painelTarefaTitulo;
    private javax.swing.JList<String> projetos;
    private javax.swing.JScrollPane tabelaListaTarefas;
    private javax.swing.JTable tabelaTarefas;
    private javax.swing.JLabel tituloListaVazia;
    // End of variables declaration//GEN-END:variables
}
