package view;

import controller.TaskController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;

public class TaskDialogScreen extends javax.swing.JDialog {

    /**
     * Creates new form taskDialogScreen
     */
    TaskController controller;
    Project project;

    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        controller = new TaskController();

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaNovaTarefa = new javax.swing.JPanel();
        cabecalho = new javax.swing.JPanel();
        cabecalhoTitulo = new javax.swing.JLabel();
        formNovaTarefa = new javax.swing.JPanel();
        inputNome = new javax.swing.JTextField();
        inputDescricao = new javax.swing.JScrollPane();
        inputTextoDescricao = new javax.swing.JTextArea();
        inputAnotacoes = new javax.swing.JScrollPane();
        inputTextoAnotacao = new javax.swing.JTextArea();
        inputPrazo = new javax.swing.JFormattedTextField();
        botaoSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        telaNovaTarefa.setBackground(new java.awt.Color(233, 218, 193));

        cabecalho.setBackground(new java.awt.Color(84, 186, 185));

        cabecalhoTitulo.setFont(new java.awt.Font("JetBrains Mono Light", 1, 14)); // NOI18N
        cabecalhoTitulo.setForeground(new java.awt.Color(251, 248, 241));
        cabecalhoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adicionar-tarefa__bege.png"))); // NOI18N
        cabecalhoTitulo.setText("Tarefa");

        javax.swing.GroupLayout cabecalhoLayout = new javax.swing.GroupLayout(cabecalho);
        cabecalho.setLayout(cabecalhoLayout);
        cabecalhoLayout.setHorizontalGroup(
            cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabecalhoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(cabecalhoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        cabecalhoLayout.setVerticalGroup(
            cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(cabecalhoTitulo)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        formNovaTarefa.setBackground(new java.awt.Color(247, 236, 222));

        inputNome.setBackground(new java.awt.Color(251, 248, 241));
        inputNome.setFont(new java.awt.Font("JetBrains Mono Light", 0, 12)); // NOI18N
        inputNome.setForeground(new java.awt.Color(0, 0, 0));
        inputNome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono Light", 0, 12), new java.awt.Color(84, 186, 186))); // NOI18N

        inputTextoDescricao.setBackground(new java.awt.Color(251, 248, 241));
        inputTextoDescricao.setColumns(20);
        inputTextoDescricao.setFont(new java.awt.Font("JetBrains Mono Light", 0, 12)); // NOI18N
        inputTextoDescricao.setForeground(new java.awt.Color(0, 0, 0));
        inputTextoDescricao.setRows(5);
        inputTextoDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descriçao", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono Light", 0, 12), new java.awt.Color(84, 186, 185))); // NOI18N
        inputDescricao.setViewportView(inputTextoDescricao);

        inputTextoAnotacao.setBackground(new java.awt.Color(251, 248, 241));
        inputTextoAnotacao.setColumns(20);
        inputTextoAnotacao.setFont(new java.awt.Font("JetBrains Mono Light", 0, 12)); // NOI18N
        inputTextoAnotacao.setForeground(new java.awt.Color(0, 0, 0));
        inputTextoAnotacao.setRows(5);
        inputTextoAnotacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Anotaçoes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono Light", 0, 12), new java.awt.Color(84, 186, 185))); // NOI18N
        inputAnotacoes.setViewportView(inputTextoAnotacao);

        inputPrazo.setBackground(new java.awt.Color(251, 248, 241));
        inputPrazo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prazo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("JetBrains Mono Light", 0, 12), new java.awt.Color(84, 186, 185))); // NOI18N
        inputPrazo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        inputPrazo.setToolTipText("");
        inputPrazo.setFont(new java.awt.Font("JetBrains Mono Light", 0, 14)); // NOI18N

        javax.swing.GroupLayout formNovaTarefaLayout = new javax.swing.GroupLayout(formNovaTarefa);
        formNovaTarefa.setLayout(formNovaTarefaLayout);
        formNovaTarefaLayout.setHorizontalGroup(
            formNovaTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formNovaTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formNovaTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputPrazo)
                    .addComponent(inputNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputDescricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addComponent(inputAnotacoes, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        formNovaTarefaLayout.setVerticalGroup(
            formNovaTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formNovaTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(inputAnotacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(inputPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        botaoSalvar.setBackground(new java.awt.Color(84, 186, 185));
        botaoSalvar.setFont(new java.awt.Font("JetBrains Mono Light", 1, 12)); // NOI18N
        botaoSalvar.setForeground(new java.awt.Color(255, 255, 255));
        botaoSalvar.setText("Salvar");
        botaoSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        botaoSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoSalvarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout telaNovaTarefaLayout = new javax.swing.GroupLayout(telaNovaTarefa);
        telaNovaTarefa.setLayout(telaNovaTarefaLayout);
        telaNovaTarefaLayout.setHorizontalGroup(
            telaNovaTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaNovaTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaNovaTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formNovaTarefa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cabecalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaNovaTarefaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        telaNovaTarefaLayout.setVerticalGroup(
            telaNovaTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaNovaTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formNovaTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaNovaTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaNovaTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSalvarMouseClicked
        // TODO add your handling code here:

        try {
            Task task = new Task();
            task.setIdProject(10);//corrigir o getId

            task.setName(inputNome.getText());
            task.setDescription(inputTextoDescricao.getText());
            task.setNotes(inputTextoAnotacao.getText());
            task.setIsCompleted(false);

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/y");
            Date deadLine = null;
            deadLine = dateFormat.parse(inputPrazo.getText());
            task.setDeadline(deadLine);
            
            controller.save(task);
            JOptionPane.showMessageDialog(rootPane, "Tarefa salva com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());

        }
        this.dispose();


    }//GEN-LAST:event_botaoSalvarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void setProject(Project project) {
        this.project = project;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JPanel cabecalho;
    private javax.swing.JLabel cabecalhoTitulo;
    private javax.swing.JPanel formNovaTarefa;
    private javax.swing.JScrollPane inputAnotacoes;
    private javax.swing.JScrollPane inputDescricao;
    private javax.swing.JTextField inputNome;
    private javax.swing.JFormattedTextField inputPrazo;
    private javax.swing.JTextArea inputTextoAnotacao;
    private javax.swing.JTextArea inputTextoDescricao;
    private javax.swing.JPanel telaNovaTarefa;
    // End of variables declaration//GEN-END:variables
}
